### ISSUE TITLE
Update to Documenter1.0. Remove .mapping field from Page

### ISSUE THREAD

**Issue by lazarusA** [LuxDL/DocumenterVitepress.jl#1]
`.mapping` is gone (https://github.com/JuliaDocs/Documenter.jl/pull/2068/files), hence the code 

[here](https://github.com/LuxDL/DocumenterVitepress.jl/blob/4cbc4ee7bbe2e67097f105d9e575a6d676ca5185/src/writer.jl#L25)

TODO. needs to be updated, no clue at the moment.

**Comment by asinghvi17** [comment]
For people looking to upgrade their own Documenter.jl modifications to v1.0: the Documenter implementation of the LaTeX backend was pretty clean and really helped me get to grips with the code!
