### ISSUE TITLE
Add DocumenterCitation.jl support

### ISSUE THREAD

**Issue by thofma** [LuxDL/DocumenterVitepress.jl#100]
Some breadcrumbs:
- Should be a package extension
- Needs to implement a "writer" akin to https://github.com/JuliaDocs/DocumenterCitations.jl/blob/477d6e3cf7ed85e51b2c183c958eef1e5a2f4add/src/bibliography_node.jl#L58

**Comment by shayandavoodii** [comment]
Can this cause problems in serving the docs locally?

**Comment by thofma** [comment]
No

**Comment by avik-pal** [comment]
This can be closed now right? https://luxdl.github.io/DocumenterVitepress.jl/v0.1.2/citations
