### ISSUE TITLE
`@repl` not rendered properly

### ISSUE THREAD

**Issue by thofma** [LuxDL/DocumenterVitepress.jl#102]
The following
````
```@repl
1 + 1
2 + 3
4 + 5
```
````
will result in an empty `julia-repl` block. The reason is that
```
julia> x
Documenter.MultiCodeBlock([...])

julia> x.codeblock
MarkdownAST.CodeBlock("@repl", "1 + 1\n2 + 3\n4 + 5")

julia> x.content
Markdown.Code[]
```
and the `join_multiblock` function only looks at the `.content` field: https://github.com/LuxDL/DocumenterVitepress.jl/blob/eac3f79d1e7c3c47a6e70b72efa91dab5ff05efa/src/writer.jl#L364
But this seems to be not quite correct. Apparently all the information is in the corresponding node. This is how it is done for LaTexWriter: https://github.com/JuliaDocs/Documenter.jl/blob/4fe9cf1237293c530633bcf0ef183b48417f23d7/src/latex/LaTeXWriter.jl#L522-L536

**Comment by asinghvi17** [comment]
Thanks for the debugging!  I should be able to get this done today!

**Comment by asinghvi17** [comment]
@thofma does [this](https://luxdl.github.io/DocumenterVitepress.jl/previews/PR104/code_example#REPL-example) work for you?

**Comment by thofma** [comment]
Thanks for the fix! I will check it later today
