### ISSUE TITLE
Missing closing back-ticks causes corrupt documentation

### ISSUE THREAD

**Issue by LilithHafner** [LuxDL/DocumenterVitepress.jl#116]
I forgot some closing backticks in a jldoctest block (fixed here https://github.com/LilithHafner/AliasTables.jl/pull/29) which should, in order of preference

1) Fail the documentation build
2) Render okay
3) Break that docstring's rendering
4) Break that docstring's rendering and some subsequent content
5) Break the whole documentation page but still show up as a pass

Right now we're at a 3 or 4 here https://aliastables.lilithhafner.com/v1.0.0/#AliasTables.probabilities

**Comment by asinghvi17** [comment]
This would probably be an issue for https://github.com/JuliaDocs/MarkdownAST.jl or https://github.com/JuliaDocs/Documenter.jl since we don't do any parsing at all in DocumenterVitepress!
