### ISSUE TITLE
v0.0.20 seems to have broken Markdown.Link 

### ISSUE THREAD

**Issue by avik-pal** [LuxDL/DocumenterVitepress.jl#134]
Sorry for being vague, I am myself not sure what is exactly broken, but CI started to fail since the release

See https://buildkite.com/julialang/lux-dot-jl/builds/2146#018f7cea-e5d8-44b6-9f15-0a14f952a577/564-7443. Builds were fine before that.

**Comment by asinghvi17** [comment]
Thanks for the report - this seems to be because the header string is now wrapped in `replace(..., "'" => "\\'")` when building the sidebar.  I should be able to get a fix out today.

**Comment by avik-pal** [comment]
This is now fixed. Thanks
