### ISSUE TITLE
Default template ignores description

### ISSUE THREAD

**Issue by jkrumbiegel** [LuxDL/DocumenterVitepress.jl#142]
the default template has `A VitePress Site` hardcoded for the description, so without creating a template manually, users will not get their custom `description` from the settings object.

**Comment by lazarusA** [comment]
so, we need another `REPLACE_ME` call here, with the content coming from `description` in index.md? and if not available have a better default? like `A site for "package_name"` 😄 .

**Comment by asinghvi17** [comment]
I merged #152 to fix that, it's just that the REPLACE_ME wasn't in the template.  Should be fixed now.
