### ISSUE TITLE
How to deploy on GitLab

### ISSUE THREAD

**Issue by Moelf** [LuxDL/DocumenterVitepress.jl#145]

**Comment by asinghvi17** [comment]
Does it not just work?

**Comment by Moelf** [comment]
It kinda doesn't

**Comment by asinghvi17** [comment]
Is there a specific error or some gitlab log you could point me to?  There are a couple of potential failure points I can see but I'm not familiar with the Gitlab deployment system these days.

**Comment by Moelf** [comment]
the deployed page is 404 on GitLab.

I *think it's because we have `build/final_site/index.html` instead of `build/index.html`?

**Comment by Moelf** [comment]
https://bjettla-jl.docs.cern.ch/


That only semi-worked, any guess?

**Comment by Moelf** [comment]
Yeah the CERN gitlab instance is closed, I can invite you to the GitHub mirror if you want.

I will do more investigation soon

**Comment by Moelf** [comment]
Btw vanilla documenter.jl worked on gitlab just fine

**Comment by asinghvi17** [comment]
Could you send a screenshot of what the website looks like to you?  Would be nice to look at the Github mirror as well.

**Comment by Moelf** [comment]
ohhhhh sorry I forgot you can't even access the website ugh, here:
![image](https://github.com/LuxDL/DocumenterVitepress.jl/assets/5306213/2d2e4c8f-08a9-43a9-aa49-e7f4ff5e6c53)


yeah, in the vanilla Documenter.jl case, moving the `docs/build` and pointing GitLab Pages build to `public` worked just fine. Basically: https://gitlab.com/ExpandingMan/Parquet2.jl/-/blob/master/.gitlab-ci.yml?ref_type=heads#L24-29

**Comment by Moelf** [comment]
hm, I guess I don't know why those js files or what not are not accessible:
```
/public> tree
.
├── 404.html
├── assets
│   ├── app.D4LdPWg3.js
│   ├── chunks
│   │   ├── framework.DImIk300.js
│   │   ├── @localSearchIndexroot.Bqfjzs4i.js
│   │   ├── theme.C5ukZYie.js
│   │   └── VPLocalSearchBox.BDC9-P7E.js
│   ├── data_schema.md.dUSeLSYC.js
│   ├── data_schema.md.dUSeLSYC.lean.js
│   ├── index.md.CXzbBlpN.js
│   ├── index.md.CXzbBlpN.lean.js
│   ├── install.md.LtQZTklO.js
│   ├── install.md.LtQZTklO.lean.js
│   ├── inter-italic-cyrillic.By2_1cv3.woff2
│   ├── inter-italic-cyrillic-ext.r48I6akx.woff2
│   ├── inter-italic-greek.DJ8dCoTZ.woff2
│   ├── inter-italic-greek-ext.1u6EdAuj.woff2
│   ├── inter-italic-latin.C2AdPX0b.woff2
│   ├── inter-italic-latin-ext.CN1xVJS-.woff2
│   ├── inter-italic-vietnamese.BSbpV94h.woff2
│   ├── internalapis.md.zd4z5DxV.js
│   ├── internalapis.md.zd4z5DxV.lean.js
│   ├── inter-roman-cyrillic.C5lxZ8CY.woff2
│   ├── inter-roman-cyrillic-ext.BBPuwvHQ.woff2
│   ├── inter-roman-greek.BBVDIX6e.woff2
│   ├── inter-roman-greek-ext.CqjqNYQ-.woff2
│   ├── inter-roman-latin.Di8DUHzh.woff2
│   ├── inter-roman-latin-ext.4ZJIpNVo.woff2
│   ├── inter-roman-vietnamese.BjW4sHH5.woff2
│   └── style.BCHh3-pm.css
├── data_schema.html
├── hashmap.json
├── index.html
├── install.html
├── internalapis.html
└── logo.png
```

**Comment by asinghvi17** [comment]
This looks like a path misconfiguration.  What are you passing to `MarkdownVitepress`?  Might be that the `deploy_url` parameter is misconfigured.

**Comment by Moelf** [comment]
oh yeah probably, I don't have `deploy_url` right now:
```julia
repopath = if haskey(ENV, "GITHUB_ACTION")
    "github.com/Moelf/BjetTLA.jl"
else
    "gitlab.cern.ch/tla-atlas-run3/BjetTLA.jl"
end

makedocs(;
         modules=[BjetTLA],
         format=DocumenterVitepress.MarkdownVitepress(repo = repopath, devbranch = "main", devurl = "dev"),

```

what should it be in this case? maybe `bjettla-jl.docs.cern.ch`?

**Comment by asinghvi17** [comment]
Yes

**Comment by Moelf** [comment]
that worked! thanks. So I think basically for DV.jl, you really got set `deploy_url` correctly, where vanilla Documenter.jl is more loose about it.

**Comment by Moelf** [comment]
huh, now github doesn't work https://moelf.github.io/BjetTLA.jl/dev/

I think:
```
deploy_url = if haskey(ENV, "GITHUB_ACTION")
    "moelf.github.io/BjetTLA.jl"
else
    "bjettla-jl.docs.cern.ch"
end

```

need to change to `    "moelf.github.io/BjetTLA.jl/dev"`, but I feel like that's a bug?

**Comment by asinghvi17** [comment]
Huh, that deploy url seems right to me...how about this: 
```
deploy_url = if haskey(ENV, "GITHUB_ACTION")
    nothing
else
    "bjettla-jl.docs.cern.ch"
end
```

**Comment by asinghvi17** [comment]
Yeah looking at the links the deploy URL is horribly misconfigured on the first one.  Handling that in DV could use quite a bit of improvement, but for now the default ought to work.
