### ISSUE TITLE
copy assets folder just before creating .documenter and final_site

### ISSUE THREAD

**Issue by lazarusA** [LuxDL/DocumenterVitepress.jl#159]
In the current implementation it looks like we copy the assets folders immediately. However, because I want to save some files coming from `doctest` blocks first, the build fails later, because those files were never copied, because they didnt' exist yet. 

Where should I be looking? @asinghvi17

**Comment by asinghvi17** [comment]
That shouldn't be the case...Markdown expansion (including explicit saving and doctests) is done in `docs/build` and only then are files copied to `docs/build/.documenter`.  This is to say that all Documenter files are executed under `cd(first(splitdir(page.path)))`.

**Comment by lazarusA** [comment]
Working here: https://github.com/rafaqz/Rasters.jl/tree/la/new_vite_docs

in a `.jl` file from the. I have
```jldoctest
savefig(a, "src/assets/api/mosaic_example_africa.png")
nothing
# output

```

### Individual continents
```
![arica](assets/api/mosaic_example_africa.png)
```
which saves the output into `docs/src/assets/api/`.  It does save things correctly there, but, then they are not copied to `.documenter`.

**Comment by asinghvi17** [comment]
try using `public` instead of `assets` maybe?

**Comment by lazarusA** [comment]
thanks for the hint!

when doing `doctests` we need to save the output into `docs/build/`, i.e., `savefig(a, "docs/build/my_ouput.png")`

**Comment by asinghvi17** [comment]
Huh, that's a bit strange.  Possibly worth an issue on Documenter.jl, since doctests should be executed in the workdir.
