### ISSUE TITLE
Issue with inline math rendering

### ISSUE THREAD

**Issue by Azzaare** [LuxDL/DocumenterVitepress.jl#161]
I don't know from when it has appeared, but there is a vertical alignment issue with inline math rendering. For instance https://luxdl.github.io/DocumenterVitepress.jl/dev/markdown-examples#equations .

It appears on several browsers on different devices and OS.

**Comment by asinghvi17** [comment]
Can confirm as well.  Will look into it!

**Comment by thofma** [comment]
Before it is lost in slack, here two comments from our local web wizard @aaruni96:
> changing `display` in CSS for the mathjax elements (`mjx-container`) from `inline-block` to `inline` fixes it for me (tested on firefox and chrome)

**Comment by aaruni96** [comment]
Sorry, I meant to write a PR for this, and then got swamped with other things. I will maybe write a PR if its still wanted in a couple weeks.
