### ISSUE TITLE
Inline LaTeX display offset 

### ISSUE THREAD

**Issue by Moelf** [LuxDL/DocumenterVitepress.jl#167]
https://juliahep.github.io/JetReconstruction.jl/previews/PR66/

Looks like 
![Screenshot_20240712_073215_Firefox Nightly](https://github.com/user-attachments/assets/d06c12e2-e4b1-412b-b607-b8a641580ab5)

**Comment by avik-pal** [comment]
Duplicate of https://github.com/LuxDL/DocumenterVitepress.jl/issues/161

**Comment by asinghvi17** [comment]
Do you have custom CSS?

**Comment by Moelf** [comment]
I don't think so. copied from templates in this repo

**Comment by asinghvi17** [comment]
OK, looks like we might be able to fix this in the repo then.  Someone over in #161 mentioned a potential fix.

**Comment by Moelf** [comment]
can report that does fix it
