### ISSUE TITLE
Inline math equations render slightly elevated

### ISSUE THREAD

**Issue by ismael-lajaaiti** [LuxDL/DocumenterVitepress.jl#174]
Inline math equations are displayed incorrectly, instead of being aligned with the text they appear slightly elevated.
For example, see the DocumenterVitepress [documentation on equation syntax](https://luxdl.github.io/DocumenterVitepress.jl/v0.1.1/markdown-examples#equations)

![image](https://github.com/user-attachments/assets/3fe994e8-0e0a-4bc9-83c7-a1326144cd82)

**Comment by lazarusA** [comment]
![Screenshot 2024-09-16 at 11 08 00](https://github.com/user-attachments/assets/dd8be958-c603-4e27-b2ea-4958be8c06a4)
this was fixed on master by https://github.com/LuxDL/DocumenterVitepress.jl/pull/169
