### ISSUE TITLE
Mathjax rendering issues on github CI

### ISSUE THREAD

**Issue by dominic-chang** [LuxDL/DocumenterVitepress.jl#185]
I'm having strange rendering issues with inline equations when building my docs with github ci. Building on github ci gives me results like this:

![Image](https://github.com/user-attachments/assets/c1ee6f96-6eb4-4937-b7a9-12fd2b832056)

while rendering on my local pc (M1 mac) gives this:

![Image](https://github.com/user-attachments/assets/3672986d-fcc8-421f-ad6e-0b99ccc09fb5)

**Comment by agdestein** [comment]
This was fixed by #169, but maybe you still have to manually update [this CSS file](https://github.com/LuxDL/DocumenterVitepress.jl/pull/169/files#diff-585f9a243ba5f04340067f35498dd3f1879be953072d480a063e673940a384c2)
