### ISSUE TITLE
Default Julia Docs Admonitions

### ISSUE THREAD

**Issue by avik-pal** [LuxDL/DocumenterVitepress.jl#22]
It would be great if we could detect the default julia admonitions

```julia
!!! note
	
	A note
```

and automatically convert them to the format `Vitepress` understands. I think going through all repositories and making the change manually can be quite painful (speaking from personal experience of having to do it once)

This also makes the docs work in REPL properly, for example, all of Lux docs in REPL show up as:

```julia
:::tip Type Stability

If your input function f is type-stable but the generated model is not type stable, it should be treated as a bug. We will appreciate issues if you find such cases.

:::

:::warning Parameter Count

Array Parameter don't print the number of parameters on the side. However, they do account for the total number of parameters printed at the bottom.

:::
```

**Comment by asinghvi17** [comment]
I already enabled this in https://github.com/LuxDL/DocumenterVitepress.jl/blob/e084788067c5b20503bb44edbe3aa6dec6cfa3ed/src/writer.jl#L392
and it seems to work - there's an example in the docs as well! https://luxdl.github.io/DocumenterVitepress.jl/dev/getting_started#Getting-started
