### ISSUE TITLE
Interactions broken on some components of homepage

### ISSUE THREAD

**Issue by LilithHafner** [LuxDL/DocumenterVitepress.jl#26]
On https://luxdl.github.io/DocumenterVitepress.jl/dev/ there are three large boxes labeled "markdown", "literate.jl", and "vue components". The reactivity works for the "markdown" box but not the other two (hovering does not cause a green outline to fade in)

EDIT: and, unlike the first box, the latter two are not clickable.

**Comment by lazarusA** [comment]
They are not broken. There is just not a link referencing those components. We should add them.

**Comment by asinghvi17** [comment]
This was fixed at some point, they seem to work now.
