### ISSUE TITLE
svg output is broken

### ISSUE THREAD

**Issue by lazarusA** [LuxDL/DocumenterVitepress.jl#41]
On master, the automatic output of images for the svg format is broken. Tested on https://github.com/lazarusA/TemplateDocsVitePress.jl

**Comment by asinghvi17** [comment]
Should be fine after this release

**Comment by lazarusA** [comment]
Output is back but, now the svg doesn't re-scales to the div width. In mobile the figures overflow to the right. Also, the literate example works locally but no online, no figure 😢.

**Comment by asinghvi17** [comment]
That is a problem.  Should it be wrapped in an image tag?

**Comment by lazarusA** [comment]
yes. It should be wrapped with img tag. That's how is working now in BeautifulMakie. Well, how it was working with version 0 :D

**Comment by asinghvi17** [comment]
I was trying to save as few files as possible :D 

but it seems as though we can pass it as base64...I'll try to do that!
