### ISSUE TITLE
doctest fails

### ISSUE THREAD

**Issue by lazarusA** [LuxDL/DocumenterVitepress.jl#47]
maybe related to the latest change to julia -> /Julia>  change. The following generates a nested ```julia /Julia> ``` md file.
````
```jldoctest dataframe
julia> using DataFrames
```

```jldoctest dataframe
julia> DataFrame()
0×0 DataFrame
```
````

**Comment by asinghvi17** [comment]
I want it to do that - `/julia>/` was supposed to highlight the `julia>` block but it doesn't seem to be working :(

**Comment by asinghvi17** [comment]
The actual doctest shouldn't be failing, though?

**Comment by lazarusA** [comment]
Mmm... they failed for DataFrames. I will take another look.

**Comment by asinghvi17** [comment]
Huh, if you could post what happened that would be good
