### ISSUE TITLE
CI Warnings with version v0.0.8

### ISSUE THREAD

**Issue by svilupp** [LuxDL/DocumenterVitepress.jl#50]
Thank you for the package!

Is it possible that there is something wrong with the latest tag (v0.0.8)?

My CI has been working until the latest version has been tagged and now I'm getting the following warnings:

> ┌ DocumenterVitepress
> │  WARNING: Method definition mime_priority(Base.Multimedia.MIME{Symbol("text/html")}) in module DocumenterVitepress at /home/runner/.julia/packages/DocumenterVitepress/vt5GZ/src/writer.jl:407 overwritten at /home/runner/.julia/packages/DocumenterVitepress/vt5GZ/src/writer.jl:417.
> │  ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
> └  
> Run # The Julia command that will be executed

**Comment by svilupp** [comment]
Okay, I think it was my mistake! I was just a coincidence... Re-running the CI

**Comment by asinghvi17** [comment]
Huh, I somehow never saw that on my machine.  Strange...will fix tomorrow!

**Comment by svilupp** [comment]
But did I mention how cool this package this?!! Seriously, thank you!
