### ISSUE TITLE
"Take me home" link broken on 404 page

### ISSUE THREAD

**Issue by LilithHafner** [LuxDL/DocumenterVitepress.jl#53]
The "take me home" link on https://chairmarks.lilithhafner.com/previews/PR35/404 links to https://chairmarks.lilithhafner.com/chairmarks.lilithhafner.com/previews/PR35/

Perhaps this has to due with using a custom domain?

**Comment by asinghvi17** [comment]
For future reference, this was a bug in the custom domain path determination code in `make_vitepress_config` which has since been fixed.
