### ISSUE TITLE
latest/master is not capturing figures's outputs

### ISSUE THREAD

**Issue by lazarusA** [LuxDL/DocumenterVitepress.jl#55]
<img width="727" alt="Screenshot 2024-03-03 at 17 44 27" src="https://github.com/LuxDL/DocumenterVitepress.jl/assets/19525261/5c18d351-a811-436f-8861-3680da7f69ac">

It works fine in `v0.0.7`.

**Comment by asinghvi17** [comment]
It's working fine so far as I can tell?  See https://asinghvi17.github.io/GeometryOps.jl/dev/source/methods/centroid which was built an hour ago

**Comment by asinghvi17** [comment]
huh, but I do see it in master, which is really strange

**Comment by asinghvi17** [comment]
oh maybe it's to do with the order of markdown writing?  let me take a look

**Comment by lazarusA** [comment]
https://lazarusa.github.io/TemplateDocsVitePress.jl/dev/plotting

**Comment by asinghvi17** [comment]
yep - it is.  will release a fix
