### ISSUE TITLE
`@` sign looks funny in code blocks [personal preference]

### ISSUE THREAD

**Issue by LilithHafner** [LuxDL/DocumenterVitepress.jl#57]
I don't like how the `@` sign looks in code blocks.

![Screenshot from 2024-03-04 10-13-07](https://github.com/LuxDL/DocumenterVitepress.jl/assets/60898866/f68d7f78-0272-4933-a1be-6313eb1d3887)

![Screenshot from 2024-03-04 10-14-13](https://github.com/LuxDL/DocumenterVitepress.jl/assets/60898866/ddbf231e-001d-4604-b449-510c83f5deda)

I prefer `@` signs more similar to [julia mono](https://juliamono.netlify.app/)

![Screenshot from 2024-03-04 10-15-55](https://github.com/LuxDL/DocumenterVitepress.jl/assets/60898866/0c677c83-3b20-4781-be71-2027ec132cc3)

This issue is entirely opinion and preference based and has no basis in facts.

**Comment by LilithHafner** [comment]
I like B! Mixing and matching fonts character by character sound bad to me.

**Comment by avik-pal** [comment]
This was because of the Space Mono Font. I recently swapped it out in Lux docs, we should do it here too. https://github.com/LuxDL/DocumenterVitepress.jl/blob/e801f8e84f561824bd24b577b5e15202373fbdf9/docs/src/.vitepress/theme/style.css#L1-L2
