### ISSUE TITLE
Stable docs point to 0.0.9

### ISSUE THREAD

**Issue by LilithHafner** [LuxDL/DocumenterVitepress.jl#58]
Stable docs point to 0.0.9 even though 0.0.10 is tagged. Hopefully this is some sort of deployment fluke and not a version sorting issue.

**Comment by asinghvi17** [comment]
Yeah the tagbot tags are somehow not causing actions to deploy - will fix that

**Comment by LilithHafner** [comment]
Is that perhaps because the tagbot is running with the GITHUB_TOKEN key and the DOCUMENTER_KEY, but the later is not set so it does not have permission to trigger another workflow? That can be fixed by running

```julia
]activate --temp
]add DocumenterTools
julia> using DocumenterTools
julia> DocumenterTools.genkeys(user="LuxDL", repo="DocumenterVitepress.jl")
```

And following the printed instructions.

**Comment by asinghvi17** [comment]
Huh that's very possible - I remember that `gh-pages` used to not deploy when committed to by github actions without that ssh key, but I guess they might have special-cased that branch?

@avik-pal would you be able to add this?  I don't have admin on this repo.

**Comment by avik-pal** [comment]
Added you as admin

**Comment by asinghvi17** [comment]
thanks!
