### ISSUE TITLE
The side bar navigation and top bar navigation have different orders

### ISSUE THREAD

**Issue by LilithHafner** [LuxDL/DocumenterVitepress.jl#59]
The side bar navigation and top bar navigation have different orders on the documenter vitepress docs.

![Screenshot from 2024-03-04 11-16-59](https://github.com/LuxDL/DocumenterVitepress.jl/assets/60898866/3a51674d-6a18-447d-ab79-fd52b8bb7353)

**Comment by asinghvi17** [comment]
That was kind of intentional (I think) - just to show that you can actually do this by setting the navbar manually in `config.mts`.
