### ISSUE TITLE
Can't find assets directory?

### ISSUE THREAD

**Issue by cormullion** [LuxDL/DocumenterVitepress.jl#65]
My attempt at a build is erroring because it can't find an assets directory:

```
┌ Warning: DocumenterVitepress: no assets directory found.
└ @ DocumenterVitepress ~/.julia/packages/DocumenterVitepress/SZzuS/src/writer.jl:228

...

build error:
RollupError: Could not resolve "./assets/figures/f.gif" from "build/.documenter/basics.md"

```

although it's unchanged from the usual Documenter.jl structure:

```plain
docs
└───src
    └───basics.md
    └───index.md
    └───.vitepress
        └───config.mts
    └───assets
        └───logo.png
        └───logo.svg
        └───styles.css
        └───figures
            └───f.gif
    └───reference
        └───api.md
        └───functionindex.md
```

Is there some  configuration option I've overlooked?

**Comment by lazarusA** [comment]
Repo? Branch?

**Comment by asinghvi17** [comment]
ah, the issue here is that we move the files in the `src/assets` folder into `.documenter/public` during the build step.  I can walk that change back and only move files matching `logo.*` and `favicon` into public instead.

**Comment by cormullion** [comment]
Yes, I'm using Markdown links such as ```![ alt text](assets/figures/figure.svg)``` (Documenter-style). I'm hoping that I wouldn't have to rewrite them all.

**Comment by lazarusA** [comment]
I see. Yes, I have the same issue. Going from assets to public (replacing/ renaming) its confusing. Maybe it should be better to keep assets as assets :D, and create the extra folder `public` in docs? and then copy both? public is mandatory in vitepress ....

**Comment by asinghvi17** [comment]
@cormullion could you try your build on the latest master?

**Comment by cormullion** [comment]
Works perfectly! 

<img width="1448" alt="Screenshot 2024-03-08 at 17 43 16" src="https://github.com/LuxDL/DocumenterVitepress.jl/assets/52289/fdc31fb3-059d-4655-89f8-e105e35c953b">

**Comment by asinghvi17** [comment]
Perfect!  That package looks really cool, by the way :)
